
# NumPy Homework Notebook

This notebook contains a series of exercises to help you practice **NumPy**.  
You will work on arrays, indexing, slicing, mathematical operations, random numbers, reshaping, and more.

**Instructions:**
- Do not use Python lists unless specifically asked.
- Use only NumPy functions for calculations.
- Answer each question in a new code cell below the question.

---


## Array Creation

1. Create a 1D array of numbers from 0 to 20.

In [295]:
import numpy as np
arr=np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

2. Create a 1D array of even numbers from 2 to 40.

In [299]:
arr=np.arange(2,41,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

3. Create a 3x3 matrix filled with zeros.

In [220]:
matrix=np.zeros((3,3),dtype = int)
matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

4. Create a 4x4 identity matrix.

In [313]:
matrix=np.eye(3,dtype= int)
matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

5. Create a 1D array of 10 random integers between 1 and 100.

In [317]:
arr= np.random.randint(1,101,10)
arr

array([27, 26, 35, 75, 21, 58, 90,  2,  9, 78])

## Array Indexing and Slicing

6. Create an array from 10 to 50. Extract only even numbers using slicing and conditions.

In [227]:
arr = np.arange(10,51)
even_condition = arr[arr % 2 == 0]
even_condition

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

7. Create a 5x5 matrix of numbers from 1 to 25. Extract the first row.

In [229]:
matrix = np.arange(1,26).reshape(5,5)
matrix
ext_row = matrix[0,:]
ext_row

array([1, 2, 3, 4, 5])

8. From the same matrix, extract the last column.

In [231]:
matrix1 = matrix[:,-1]
matrix1

array([ 5, 10, 15, 20, 25])

9. From the same matrix, extract the sub-matrix [[7,8],[12,13]].

In [233]:
sub_matrix= matrix[1:3, 1:3]
sub_matrix

array([[ 7,  8],
       [12, 13]])

10. Reverse a NumPy array.

In [235]:
reversed_arr = arr[::-1]
reversed_arr

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

## Array Operations

11. Create two arrays: [1,2,3,4,5] and [6,7,8,9,10]. Perform element-wise addition, subtraction, multiplication, and division.

In [238]:
arr1= np.array([1, 2, 3, 4, 5])
arr2= np.array([6, 7, 8, 9, 10])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


12. Compute the square of every element in an array.

In [240]:
square_1 = arr1 ** 2
square_2 = arr2 ** 2
print(square_1)
print(square_2)

[ 1  4  9 16 25]
[ 36  49  64  81 100]


13. Compute the sum of all elements in a NumPy array.

In [242]:
print(arr1.sum())
print(arr2.sum())


15
40


14.Compute the mean, median, and standard deviation of a random array of size 20.

In [244]:
arr = np.random.rand(20)
arr
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

0.6206621588311135
0.6374183043793002
0.24152900399344435


15. Normalize an array (subtract mean and divide by standard deviation).

In [246]:
mean = np.mean(arr)
std = np.std(arr)
Stand = (arr- mean) / std
print(Stand)
print(np.round(Stand, 2))

[ 0.47133362  0.95943514 -0.01764854 -0.10324289  0.15639912  0.30240145
 -0.48279082  0.39107906  0.85794825 -0.79367752  1.50795045  1.00015875
 -0.1689132  -1.64325451 -1.17913709 -2.41266982  0.77089365  1.56888172
 -0.64770733 -0.53743952]
[ 0.47  0.96 -0.02 -0.1   0.16  0.3  -0.48  0.39  0.86 -0.79  1.51  1.
 -0.17 -1.64 -1.18 -2.41  0.77  1.57 -0.65 -0.54]


## Reshaping and Stacking

16. Create a 1D array of numbers from 1 to 12. Reshape it into a 3x4 matrix.

In [329]:
arr = np.arange(1,13)
arr
matrix = arr.reshape(3,4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


17. Flatten a 2D array into a 1D array.

In [355]:
matrix = np.arange(1,10).reshape(3,3)
arr1D= matrix.flatten()
print(matrix)
print(arr1D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


18.Stack two arrays vertically.

In [369]:
arr1=np.array([1,5,6,8,9])
arr2=np.array([7,9,11,12,15])
arrstack = np.vstack((arr1,arr2))
arrstack

array([[ 1,  5,  6,  8,  9],
       [ 7,  9, 11, 12, 15]])

19. Stack two arrays horizontally.

In [371]:
arr1=np.array([1,5,6,8,9])
arr2=np.array([7,9,11,12,15])
arrstack = np.hstack((arr1,arr2))
arrstack

array([ 1,  5,  6,  8,  9,  7,  9, 11, 12, 15])

20. Split a 1D array of size 10 into two equal parts.

In [379]:
arr=np.arange(1,11)
part1,part2=np.split(arr,2)
print(part1)
print(part2)

[1 2 3 4 5]
[ 6  7  8  9 10]


## Random Numbers

21. Generate an array of 15 random numbers from a normal distribution.

In [393]:
arr=np.random.randn(15)
arr

array([ 0.13966621,  1.68050604,  1.62297557,  0.94139229, -1.51909726,
       -0.38939653, -0.6385822 ,  0.48190362,  1.00160997, -0.61789952,
        0.25306449,  0.77897311, -0.72681541,  0.22839966,  0.80600482])

22. Generate a 3x3 matrix of random integers between 1 and 50.

In [411]:
matrix=np.random.randint(1,51,9).reshape(3,3)
matrix

array([[32, 47, 18],
       [22,  6, 48],
       [ 3, 34, 34]])

23. Set the seed to 42 and generate a 1D array of 5 random numbers.

In [417]:
np.random.seed(42)
arr=np.random.rand(5)
arr

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

24. Shuffle an array of numbers from 1 to 10.

In [429]:
arr=np.arange(1,11)
np.random.shuffle(arr)
arr

array([ 9,  3,  6,  8,  4,  2, 10,  1,  5,  7])

25.Generate 1000 random numbers and compute their histogram.

In [447]:
arr=np.random.randn(1000)
hist, bin_edges =np.histogram(arr,bins=10)
print(hist)
print(bin_edges)

[  1  12  29  93 198 267 218 131  39  12]
[-3.70879661 -3.05382831 -2.39886001 -1.74389171 -1.08892341 -0.43395511
  0.22101319  0.87598149  1.53094979  2.18591809  2.84088639]


## Linear Algebra with NumPy

26. Create a 2x2 matrix and compute its determinant.

In [471]:
matrix= np.arange(1,5).reshape(2,2)
print(matrix)
print(round(np.linalg.det(matrix)))

[[1 2]
 [3 4]]
-2


27. Compute the inverse of a 3x3 matrix.

In [497]:
matrix=np.random.rand(3,3)
print(matrix)
print(np.linalg.inv(matrix))

[[0.3056485  0.5929827  0.53768352]
 [0.00471243 0.0723894  0.29036821]
 [0.88223508 0.14701495 0.71089433]]
[[ 0.07394755 -2.88701885  1.12328667]
 [ 2.13110545 -2.16698447 -0.72674216]
 [-0.53248912  4.0309907   0.16294836]]


28. Perform matrix multiplication on two compatible matrices.

In [515]:
MatA = np.random.rand(3,2)
MatB = np.random.rand(2,3)
print(MatA)
print(MatB)
print(MatA @ MatB)

[[0.63613367 0.45421442]
 [0.86343001 0.91696111]
 [0.99680771 0.15368414]]
[[0.86296405 0.26602138 0.59081587]
 [0.50577283 0.01798813 0.93277128]]
[[0.7786898  0.17739562 0.79951604]
 [1.20888308 0.24618526 1.36544315]
 [0.93793848 0.26793665 0.73228197]]


29. Compute the eigenvalues and eigenvectors of a 2x2 matrix.

In [519]:
matrix = np.array(
   [[4, 1],
    [2, 3] ])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[5. 2.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


30. Solve the system of linear equations: 2x + y = 5, x - y = 1.

In [521]:
X = np.array([
    [2, 1],
    [1, -1]
])

Y = np.array([5, 1])

solution = np.linalg.solve(X, Y)

print(solution)

[2. 1.]
